---

- name: add deadsnakes repository
  apt_repository: repo="ppa:fkrull/deadsnakes" update_cache=yes

- name: install python {{ python_version }}
  apt: name=python{{ python_version }} state=present

- name: install python {{ python_version }} dev
  apt: name=python{{ python_version }}-dev state=present
  
- name: install libncurses5-dev
  apt: name=libncurses5-dev state=present
